# Generated by Django 5.0 on 2024-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrperformance', '0002_alter_attendancerecord_timein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='timein',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timeout',
            field=models.DateTimeField(blank=True),
        ),
    ]
