# Generated by Django 5.0 on 2024-02-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrperformance', '0004_alter_attendancerecord_timein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='timein',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timeout',
            field=models.DateTimeField(null=True),
        ),
    ]
