# Generated by Django 5.0 on 2024-02-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrperformance', '0005_alter_attendancerecord_timein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='type',
            field=models.ForeignKey(blank=True, default='Normal', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrperformance.timelogtype'),
        ),
    ]
