# Generated by Django 5.0 on 2024-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrperformance', '0007_alter_attendancerecord_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timein_setpoint', models.TimeField(null=True)),
                ('timeout_setpoint', models.TimeField(null=True)),
            ],
        ),
    ]
