# Generated by Django 5.0 on 2024-02-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_profile_picture'),
        ('hrperformance', '0008_hrsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsetting',
            name='awol_offense_suspension',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='awol_offense_verbalwarning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='awol_offense_writtenwarning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='awol_setpoint',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='break_time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='break_time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='late_offense_suspension',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='late_offense_verbalwarning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hrsetting',
            name='late_offense_writtenwarning',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('description', models.CharField(null=True)),
                ('status', models.CharField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(null=True)),
                ('description', models.TextField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
