# Generated by Django 5.0 on 2024-02-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrperformance', '0009_hrsetting_awol_offense_suspension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offense',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
