# Generated by Django 5.0 on 2024-01-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='employee_id_no',
        ),
    ]
