# Generated by Django 5.0 on 2024-01-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_employee_id_employee_employee_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(default='stellarhr-default-image.jpg', upload_to='profile'),
        ),
    ]
